### ISSUE TITLE
buildroot files should not be in this repo

### ISSUE THREAD

**Issue by tdawson** [minimization/content-resolver-input#424]
The buildroot files are causing delays and problems for maintainers to manually change their yaml files, and it is only going to get worse.
I've found it takes between 2 and 5 minutes to simply clone the repo.
When manually editing a yaml file, I often have to re-pull and merge because buildroot has changed.
The git repo is currently at 750M.

All of these problems are going to get worse as time progresses.
We need a different way to get the buildroot information to Content Resolver

**Comment by asamalik** [comment]
Wow, that is terrible.

Let's definitely get rid of these and have a different way for the buildroot to get to Content Resolver.

**Comment by asamalik** [comment]
I'll unfortunately need force push to this repo to clean it up.

For archiving purposes, I've created [minimization/content-resolver-input-archive](https://github.com/minimization/content-resolver-input-archive) where I've pushed the current unchanged tree. 

To get this done as quickly as possible, I've also created [minimization/content-resolver-input-additional](https://github.com/minimization/content-resolver-input-additional) which we're gonna use for the large files now.

This repo remains used for configuration as before.

**Comment by tdawson** [comment]
Could you add me, and square1-box as people who can push to the new minimization/content-resolver-input-additional repo.  We can't currently, so I can't change the buildroot-generator to start using that.

**Comment by tdawson** [comment]
I have buildroot-generator setup to use minimization/content-resolver-input-additional but square1-box still cannot push to it.

**Comment by keszybz** [comment]
This can be closed.
